obstacle_range: 4
raytrace_range: 6
footprint: [[0.12, 0.12], [0.12, -0.12], [-0.12, -0.12], [-0.12, 0.12]]
inflation_radius: 0.5
transform_tolerance: 0.5
use_dijkstra: true
use_grid_path: false  

observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true



map_type: costmap